version: "3.9"
services:
  jenkins:
    container_name: jenkins_dev
    image: jenkins/dotnet
    build:
      context: dockerindockerjenkins
    ports:
      - 8080:8080
    volumes:
      - V:/jenkins_home:/var/jenkins_home
    networks:
      - net
  rabbitmq:
    container_name: rabbitmq_dev
    image: rabbitmq:3.9-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - V:/rabbitmq_home:/var/rabbitmq_home
    networks:
      - net
  mssql:
    container_name: mssql_dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Master@123
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - V:/mssql_home:/var/mssql_home
    networks:
      - net
  mysql:
    container_name: mysql_dev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - V:/mysql_home:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Master@123
    ports:
      - 3306:3306
    networks:
      - net
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - 5341:80
    volumes:
      - V:/seq_home:/var/seq_home
    environment:
      - ACCEPT_EULA=Y
    networks:
      - net
  zookeeper:
    container_name: zookeeper_dev
    image: confluentinc/cp-zookeeper:latest
    volumes: 
      - V:/zookeeper_home/data:/var/lib/zookeeper/data
      - V:/zookeeper_home/log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks: 
      - net
  kafka:
    container_name: kafka_dev
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    volumes:
      - V:/kafka_home:/var/lib/kafka
    networks: 
      - net
  grafana:
    container_name: grafana_dev
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - net
  graphite:
    container_name: graphite_dev
    image: hopsoft/graphite-statsd
    ports:
      - 81:81
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    networks:
      - net
  glue_jupyter:
    container_name: glue_jupyter
    command: /home/glue_user/jupyter/jupyter_start.sh
    environment:
      - DISABLE_SSL=true
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    ports:
      - 4040:4040
      - 18080:18080
      - 8998:8998
      - 8888:8888
    restart: always
    volumes:
      - V:/glue_jupyter:/home/glue_user/.aws
      - V:/glue_jupyter_workspace/:/home/glue_user/workspace/jupyter_workspace/
networks:
  net:
